nelmio_api_doc:
  documentation:
    info:
      title: Bookly API
      description: API documentation for Bookly application
      version: 1.0.0
    components:
      securitySchemes:
        BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - BearerAuth: []
  areas:
    default:
      path_patterns:
        - ^/api/v1
